### ISSUE TITLE
importerror

### ISSUE THREAD

**Issue by webbrowser11** [Grattapitone/FLL-Challenge#4]
Traceback (most recent call last):
  File "c:\Users\Graham\Downloads\RealCoordinateSystem.py", line 2, in <module>
    from hub import port, motion_sensor
ImportError: cannot import name 'port' from 'deeplake' (C:\Users\Graham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\deeplake\__init__.py)

**Comment by webbrowser11** [comment]
that didnt work even after i installed: motor runloop and hub.

**Comment by Grattapitone** [comment]
This is only intended for **LEGO** spike prime, I don't think you'll be able to run this in normal python. You're welcome to contribute though if you have Spike prime too.

**Comment by Grattapitone** [comment]
How did you find the repo btw. ? :)

**Comment by webbrowser11** [comment]
"This is only intended for LEGO spike prime, I don't think you'll be able to run this in normal python. You're welcome to contribute though if you have Spike prime too." then why didn't you include that in the readme or smth? anyways.... i went to @AllergenStudios then went to the profile of one of his followers: @Alastrantia then found he/she idk really contributed to this repo AND CLICKED ON IT. there is how i found the repo.

**Comment by webbrowser11** [comment]
anyways yeah im closing now
